import Head from "next/head";
import Image from "next/image";
import AppLayout from "../components/AppLayout";
import { colors } from "../styles/theme";
import Button from "../components/button";
import GitHub from "../components/icons/GitHub";
import { loginWithGithub } from "../firebase/client";



export default function Home() {

  function handleClick(event) {
    loginWithGithub().then(user=>{
      console.log(user);
    }).catch(error=>console.log(error))
  }
  return (
    <div>
      <Head>
          <title>Devter 🌎</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Image src="/devter-logo.png" alt="Logo" width={120} height={110}/>
          <h1>Devter</h1>
          <h2>Talk about development with developers</h2>
          <div>
            <Button onClick={handleClick}>
              <GitHub fill={'#fff'} width={32} height={32}/>
              Login with GitHub
            </Button>
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        div{
          margin-top:15px;
        }
        h1{
          color: ${colors.primary}
        }
        h2{
          color: ${colors.secondary}
        }
        section{
          display: grid;
          place-items:center;
          place-content:center;
          height: 100%;
        }
        `}</style>

    </div>
  );
}
