import Head from 'next/head'
import AppLayout from '@c/AppLayout'
import { colors } from '../styles/theme'
import Button from '@c/Button'
import GitHub from '@c/icons/GitHub'
import Logo from '@c/icons/Logo'
import Image from 'next/image'
import useUser, { USER_STATES } from 'Hooks/useUser'
import { loginWithGithub } from '../firebase/client'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Home () {
  const user = useUser()
  const router = useRouter()

  function handleClick (event) {
    loginWithGithub().catch((error) => console.log(error))
  }
  useEffect(() => {
    user && router.replace('/home')
  }, [user])
  return (
    <div>
      <Head>
        <title>Devter 🌎</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Logo width='100'/>
          <h1>Devter</h1>
          <h2>Talk about development with developers</h2>
          <div>
            {user === USER_STATES.NOT_LOGGED && (
              <Button onClick={handleClick}>
                <GitHub fill={'#fff'} width={32} height={32} />
                Login with GitHub
              </Button>

            )}
            {
              user === USER_STATES.NOT_KNOWN && <Image src={'/spinner.gif'} width={30} height={30}/>
            }
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        div {
          margin-top: 15px;
        }
        h1 {
          color: ${colors.primary};
          font-size: 32px;
        }
        h2 {
          color: ${colors.secondary};
        }
        section {
          display: grid;
          place-items: center;
          place-content: center;
          height: 100%;
        }
      `}</style>
    </div>
  )
}
